//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1_C__BootCamp_301_EFProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BootCampTravelDbEntities : DbContext
    {
        public BootCampTravelDbEntities()
            : base("name=BootCampTravelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerTbl> CustomerTbls { get; set; }
        public virtual DbSet<GuideTBL> GuideTBLs { get; set; }
        public virtual DbSet<LocationTBL> LocationTBLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AdminTBL> AdminTBLs { get; set; }
    }
}
